name: Deploy to Digital Ocean
permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            # Ensure UV is Installed
            curl -LsSf https://astral.sh/uv/install.sh | sh &&
            source $HOME/.cargo/env &&

            cd ${{ secrets.DO_APP_DIR }} &&
            git pull origin main &&

            # Sync Dependencies
            $HOME/.local/bin/uv sync --frozen &&

            # Run Manage Commands
            $HOME/.local/bin/uv run manage.py collectstatic --noinput &&
            $HOME/.local/bin/uv run manage.py migrate &&

            # Restart Services
            sudo systemctl restart gunicorn &&
            sudo systemctl daemon-reload &&
            sudo systemctl restart nginx
          EOF
